version: '3.9'

services:
  front-app:
    container_name: front-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_GATEWAY_URL=http://api-gateway:8080
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge
    external: true
